export const spanishTerms = (
    <div>
        <h4>1. Introducción</h4>
        <p>¡Bienvenido a iGamingPlatform ("Compañía", "nosotros", "nuestro", "nos")!</p>
        <p>Estos Términos de servicio ("Términos", "Términos de servicio") rigen el uso de nuestro sitio web ubicado en OnlineBetting.com (juntos o individualmente "Servicio") operado por iGamingPlatform.</p>
        <p>Nuestra Política de privacidad también rige el uso de nuestro Servicio y explica cómo recopilamos, protegemos y divulgamos la información que resulta del uso de nuestras páginas web.</p>
        <p>Su acuerdo con nosotros incluye estos Términos y nuestra Política de privacidad ("Acuerdos"). Usted reconoce que ha leído y comprendido los Acuerdos y acepta estar sujeto a ellos.</p>
        <p>Si no está de acuerdo con (o no puede cumplir con) los Acuerdos, entonces no puede utilizar el Servicio, pero háganoslo saber enviándonos un correo electrónico a iGamingPlatform@betting-support.com para que podamos intentar encontrar una solución. Estos Términos se aplican a todos los visitantes, usuarios y otras personas que deseen acceder o utilizar el Servicio.</p>
        <h4>2. Comunicaciones</h4>
        <p>Al utilizar nuestro Servicio, acepta suscribirse a boletines, materiales promocionales o de marketing y otra información que podamos enviar. Sin embargo, puede optar por no recibir ninguna o todas estas comunicaciones de nuestra parte siguiendo el enlace para cancelar la suscripción o enviando un correo electrónico a iGamingPlatform@betting-support.com.</p>
        <h4>3. Compras</h4>
        <p>Si desea comprar cualquier producto o servicio disponible a través del Servicio ("Compra"), es posible que se le solicite que proporcione cierta información relevante para su Compra, que incluye, entre otros, el número de su tarjeta de crédito o débito, la fecha de vencimiento de su tarjeta, su dirección de facturación y su información de envío.</p>
        <p>Usted declara y garantiza que: (i) tiene el derecho legal de usar cualquier tarjeta u otro método de pago en relación con cualquier Compra; y que (ii) la información que nos proporciona es verdadera, correcta y completa.</p>
        <p>Podemos emplear el uso de servicios de terceros con el fin de facilitar el pago y la realización de Compras. Al enviar su información, nos otorga el derecho de proporcionar la información a estos terceros sujetos a nuestra Política de privacidad.</p>
        <p>Nos reservamos el derecho de rechazar o cancelar su pedido en cualquier momento por motivos que incluyen, entre otros: disponibilidad del producto o servicio, errores en la descripción o el precio del producto o servicio, error en su pedido u otros motivos.< /p>
        <p>Nos reservamos el derecho de rechazar o cancelar su pedido si se sospecha de fraude o de una transacción no autorizada o ilegal.</p>
        <h4>4. Concursos, Sorteos y Promociones</h4>
        <p>Todos los concursos, sorteos u otras promociones (colectivamente, "Promociones") disponibles a través del Servicio pueden regirse por reglas que son independientes de estos Términos de servicio. Si participa en alguna Promoción, revise las reglas aplicables, así como nuestra Política de Privacidad. Si las reglas de una Promoción entran en conflicto con estos Términos de servicio, se aplicarán las reglas de la Promoción.</p>
        <h4>5. Suscripciones</h4>
        <p>Algunas partes del Servicio se facturan por suscripción ("Suscripción(es)"). Se le facturará por adelantado de forma recurrente y periódica ("Ciclo de facturación"). Los ciclos de facturación se establecerán según el tipo de plan de suscripción que seleccione al comprar una Suscripción.</p>
        <p>Al final de cada Ciclo de facturación, su Suscripción se renovará automáticamente bajo exactamente las mismas condiciones, a menos que usted la cancele o iGamingPlatform la cancele. Puede cancelar la renovación de su Suscripción a través de la página de administración de su cuenta en línea o comunicándose con el equipo de atención al cliente de iGamingPlatform@betting-support.com.</p>
        <p>Se requiere un método de pago válido para procesar el pago de su suscripción. Deberá proporcionar a iGamingPlatform información de facturación precisa y completa que puede incluir, entre otros, el nombre completo, la dirección, el estado, el código postal, el número de teléfono y la información de un método de pago válido. Al enviar dicha información de pago, automáticamente autoriza a iGamingPlatform a cobrar todas las tarifas de Suscripción incurridas a través de su cuenta a dichos instrumentos de pago.</p>
        <p>Si la facturación automática no se produce por algún motivo, iGamingPlatform se reserva el derecho de cancelar su acceso al Servicio con efecto inmediato.</p>
        <h4>6. Prueba gratuita</h4>
        <p>iGamingPlatform puede, a su exclusivo criterio, ofrecer una Suscripción con una prueba gratuita durante un período de tiempo limitado ("Prueba gratuita").</p>
        <p>Es posible que deba ingresar su información de facturación para registrarse en la prueba gratuita.</p>
        <p>Si ingresa su información de facturación al registrarse para la Prueba gratuita, iGamingPlatform no le cobrará hasta que la Prueba gratuita haya vencido. En el último día del período de prueba gratuito, a menos que haya cancelado su Suscripción, se le cobrarán automáticamente las tarifas de Suscripción correspondientes al tipo de Suscripción que haya seleccionado.</p>
        <p>En cualquier momento y sin previo aviso, iGamingPlatform se reserva el derecho de (i) modificar los Términos de servicio de la oferta de prueba gratuita o (ii) cancelar dicha oferta de prueba gratuita.</p>
        <h4>7. Cambios de tarifas</h4>
        <p>iGamingPlatform, a su exclusivo criterio y en cualquier momento, puede modificar las tarifas de Suscripción para las Suscripciones. Cualquier cambio en la tarifa de Suscripción entrará en vigencia al final del Ciclo de Facturación vigente en ese momento.</p>
        <p>iGamingPlatform le proporcionará un aviso previo razonable de cualquier cambio en las tarifas de Suscripción para darle la oportunidad de cancelar su Suscripción antes de que dicho cambio entre en vigencia.</p>
        <p>Su uso continuado del Servicio después de que el cambio de la tarifa de Suscripción entre en vigencia constituye su acuerdo de pagar el monto de la tarifa de Suscripción modificada.</p>
        <h4>8. Reembolsos</h4>
        <p>Emitimos reembolsos por Contratos dentro de los 10 días posteriores a la compra original del Contrato.</p>
        <h4>9. Contenido</h4>
        <p>Nuestro Servicio le permite publicar, vincular, almacenar, compartir y poner a disposición cierta información, texto, gráficos, videos u otro material ("Contenido"). Usted es responsable del Contenido que publique en o a través del Servicio, incluida su legalidad, confiabilidad y adecuación.</p>
        <p>Al publicar Contenido en o a través del Servicio, usted declara y garantiza que: (i) el Contenido es suyo (es de su propiedad) y/o tiene el derecho de usarlo y el derecho de otorgarnos los derechos y la licencia según lo dispuesto en estos Términos, y (ii) que la publicación de su Contenido en o a través del Servicio no viola los derechos de privacidad, los derechos de publicidad, los derechos de autor, los derechos de contrato o cualquier otro derecho de cualquier persona o entidad. Nos reservamos el derecho de cancelar la cuenta de cualquier persona que infrinja los derechos de autor.</p>
        <p>Usted conserva todos y cada uno de sus derechos sobre cualquier Contenido que envíe, publique o muestre en o a través del Servicio y es responsable de proteger esos derechos. No asumimos ninguna responsabilidad por el Contenido que usted o cualquier tercero publique en o a través del Servicio. Sin embargo, al publicar Contenido utilizando el Servicio, nos otorga el derecho y la licencia para usar, modificar, realizar públicamente, mostrar públicamente, reproducir y distribuir dicho Contenido en y a través del Servicio. Usted acepta que esta licencia incluye el derecho de que hagamos que su Contenido esté disponible para otros usuarios del Servicio, quienes también pueden usar su Contenido sujeto a estos Términos.</p>
        <p>iGamingPlatform tiene el derecho pero no la obligación de monitorear y editar todo el Contenido proporcionado por los usuarios.</p>
        <p>Además, el Contenido que se encuentra en este Servicio o a través de este es propiedad de iGamingPlatform o se usa con permiso. No puede distribuir, modificar, transmitir, reutilizar, descargar, volver a publicar, copiar o usar dicho Contenido, ya sea en su totalidad o en parte, con fines comerciales o para beneficio personal, sin nuestro expreso permiso previo por escrito.</p>
        <h4>10. Usos Prohibidos</h4>
        <p>Puede usar el Servicio solo para fines lícitos y de acuerdo con los Términos. Usted acepta no utilizar el Servicio:</p>
        <p>0,1. De cualquier manera que viole cualquier ley o regulación nacional o internacional aplicable.</p>
        <p>0,2. Con el propósito de explotar, dañar o intentar explotar o dañar a menores de cualquier manera exponiéndolos a contenido inapropiado o de otra manera.</p>
        <p>0,3. Para transmitir o procurar el envío de cualquier material publicitario o promocional, incluido cualquier "correo basura", "carta en cadena", "spam" o cualquier otra solicitud similar.</p>
        <p>0,4. Suplantar o intentar suplantar a la Empresa, a un empleado de la Empresa, a otro usuario o a cualquier otra persona o entidad.</p>
        <p>0,5. De cualquier manera que infrinja los derechos de otros, o que de alguna manera sea ilegal, amenazante, fraudulento o dañino, o en conexión con cualquier propósito o actividad ilegal, fraudulenta o dañina.</p>
        <p>0,6. Participar en cualquier otra conducta que restrinja o inhiba el uso o disfrute del Servicio por parte de cualquier persona, o que, según lo determinemos nosotros, pueda dañar u ofender a la Compañía o a los usuarios del Servicio o exponerlos a responsabilidad.</p>
        <p>Además, acepta no:</p>
       <p>0,1. Usar el Servicio de cualquier manera que pueda deshabilitar, sobrecargar, dañar o perjudicar el Servicio o interferir con el uso del Servicio por parte de cualquier otra parte, incluida su capacidad para participar en actividades en tiempo real a través del Servicio.</p>
        <p>0,2. Usar cualquier robot, araña u otro dispositivo, proceso o medio automático para acceder al Servicio para cualquier propósito, incluido el monitoreo o la copia de cualquier material en el Servicio.</p>
        <p>0,3. Usar cualquier proceso manual para monitorear o copiar cualquiera de los materiales en el Servicio o para cualquier otro propósito no autorizado sin nuestro consentimiento previo por escrito.</p>
        <p>0,4. Usar cualquier dispositivo, software o rutina que interfiera con el correcto funcionamiento del Servicio.</p>
        <p>0,5. Introducir virus, caballos de Troya, gusanos, bombas lógicas u otro material que sea malicioso o tecnológicamente dañino.</p>
        <p>0,6. Intentar obtener acceso no autorizado, interferir con, dañar o interrumpir cualquier parte del Servicio, el servidor en el que se almacena el Servicio o cualquier servidor, computadora o base de datos conectada al Servicio.</p>
        <p>0,7. Servicio de ataque a través de un ataque de denegación de servicio o un ataque de denegación de servicio distribuido.</p>
        <p>0,8. Tomar cualquier acción que pueda dañar o falsear la calificación de la Compañía.</p>
        <p>0,9. De lo contrario, intente interferir con el correcto funcionamiento del Servicio.</p>
        <h4>11. Análisis</h4>
        <p>Podemos utilizar Proveedores de Servicios de terceros para monitorear y analizar el uso de nuestro Servicio.</p>
        <h4>12. Prohibido el uso por menores</h4>
        <p>El servicio está destinado únicamente para el acceso y uso de personas mayores de dieciocho (18) años. Al acceder o utilizar el Servicio, usted garantiza y declara que tiene al menos dieciocho (18) años de edad y que tiene plena autoridad, derecho y capacidad para celebrar este acuerdo y cumplir con todos los términos y condiciones de los Términos. Si no tiene al menos dieciocho (18) años, tiene prohibido tanto el acceso como el uso del Servicio.</p>
        <h4>13. Cuentas</h4>
        <p>Cuando crea una cuenta con nosotros, garantiza que tiene más de 18 años y que la información que nos proporciona es precisa, completa y actual en todo momento. La información inexacta, incompleta u obsoleta puede resultar en la terminación inmediata de su cuenta en el Servicio.</p>
        <p>Usted es responsable de mantener la confidencialidad de su cuenta y contraseña, lo que incluye, entre otros, la restricción de acceso a su computadora y/o cuenta. Usted acepta aceptar la responsabilidad por todas y cada una de las actividades o acciones que ocurran bajo su cuenta y/o contraseña, ya sea que su contraseña sea con nuestro Servicio o con un servicio de terceros. Debe notificarnos de inmediato al darse cuenta de cualquier violación de seguridad o uso no autorizado de su cuenta.</p>
        <p>No puede usar como nombre de usuario el nombre de otra persona o entidad o que no esté legalmente disponible para su uso, un nombre o marca registrada que esté sujeta a cualquier derecho de otra persona o entidad que no sea usted, sin la autorización correspondiente. No puede usar como nombre de usuario ningún nombre que sea ofensivo, vulgar u obsceno.</p>
        <p>Nos reservamos el derecho de rechazar el servicio, cancelar cuentas, eliminar o editar contenido o cancelar pedidos a nuestro exclusivo criterio.</p>
        <h4>14. Propiedad Intelectual</h4>
        <p>El Servicio y su contenido original (excluyendo el Contenido proporcionado por los usuarios), las características y la funcionalidad son y seguirán siendo propiedad exclusiva de iGamingPlatform y sus licenciantes. El servicio está protegido por derechos de autor, marcas registradas y otras leyes de países extranjeros. Nuestras marcas comerciales no se pueden utilizar en relación con ningún producto o servicio sin el consentimiento previo por escrito de iGamingPlatform.</p>
        <h4>15. Política de derechos de autor</h4>
        <p>Respetamos los derechos de propiedad intelectual de otros. Es nuestra política responder a cualquier reclamo de que el Contenido publicado en el Servicio infringe los derechos de autor u otros derechos de propiedad intelectual ("Infracción") de cualquier persona o entidad.</p>
        <p>Si es propietario de derechos de autor, o está autorizado en nombre de uno, y cree que el trabajo protegido por derechos de autor se ha copiado de una manera que constituye una infracción de derechos de autor, envíe su reclamo por correo electrónico a iGamingPlatform@betting-support.com, con el asunto: "Infracción de derechos de autor" e incluya en su reclamación una descripción detallada de la supuesta infracción como se detalla a continuación, en "Aviso y procedimiento de la DMCA para reclamaciones por infracción de derechos de autor"</p>
        <p>Puede ser responsable de los daños (incluidos los costos y los honorarios de los abogados) por declaraciones falsas o reclamos de mala fe sobre la infracción de cualquier Contenido que se encuentre en y/o a través del Servicio de sus derechos de autor.</p>
        <h4>16. Aviso de DMCA y procedimiento para reclamos por infracción de derechos de autor</h4>
        <p>Puede enviar una notificación de conformidad con la Ley de derechos de autor del milenio digital (DMCA) proporcionando a nuestro agente de derechos de autor la siguiente información por escrito (consulte 17 U.S.C 512(c)(3) para obtener más detalles):</p>
        <p>0,1. una firma electrónica o física de la persona autorizada para actuar en nombre del propietario de los derechos de autor;</p>
        <p>0,2. una descripción del trabajo protegido por derechos de autor que afirma que se ha infringido, incluida la URL (es decir, la dirección de la página web) de la ubicación donde existe el trabajo protegido por derechos de autor o una copia del trabajo protegido por derechos de autor;</p>
        <p>0,3. identificación de la URL u otra ubicación específica en el Servicio donde se encuentra el material que usted afirma que está infringiendo;</p>
        <p>0,4. su dirección, número de teléfono y dirección de correo electrónico;</p>
        <p>0,5. una declaración suya de que cree de buena fe que el uso en disputa no está autorizado por el propietario de los derechos de autor, su agente o la ley;</p>
        <p>0,6. una declaración suya, hecha bajo pena de perjurio, de que la información anterior en su notificación es precisa y que usted es el propietario de los derechos de autor o está autorizado para actuar en nombre del propietario de los derechos de autor.</p>
        <p>Puede ponerse en contacto con nuestro agente de derechos de autor por correo electrónico en iGamingPlatform@betting-support.com.</p>
        <h4>17. Informes de errores y comentarios</h4>
        <p>Puede proporcionarnos directamente a iGamingPlatform@betting-support.com o a través de sitios y herramientas de terceros información y comentarios sobre errores, sugerencias de mejoras, ideas, problemas, quejas y otros asuntos relacionados con nuestro Servicio (" Retroalimentación"). Usted reconoce y acepta que: (i) no conservará, adquirirá ni hará valer ningún derecho de propiedad intelectual u otro derecho, título o interés en los Comentarios; (ii) la Compañía puede tener ideas de desarrollo similares a los Comentarios; (iii) los comentarios no contienen información confidencial o información de propiedad de usted o de un tercero; y (iv) la Compañía no tiene ninguna obligación de confidencialidad con respecto a los Comentarios. En caso de que la transferencia de la propiedad de los Comentarios no sea posible debido a las leyes obligatorias aplicables, usted otorga a la Compañía y sus afiliados un derecho de uso exclusivo, transferible, irrevocable, gratuito, sublicenciable, ilimitado y perpetuo ( incluyendo copiar, modificar, crear trabajos derivados, publicar, distribuir y comercializar) Comentarios de cualquier manera y para cualquier propósito.</p>
        <h4>18. Enlaces a otros sitios web</h4>
        <p>Nuestro Servicio puede contener enlaces a sitios web o servicios de terceros que no son propiedad ni están controlados por iGamingPlatform.</p>
        <p>iGamingPlatform no tiene control ni asume ninguna responsabilidad por el contenido, las políticas de privacidad o las prácticas de los sitios web o servicios de terceros. No garantizamos las ofertas de ninguna de estas entidades/individuos o sus sitios web.</p>
        <p>Por ejemplo, los Términos de uso descritos se crearon con PolicyMaker.io, una aplicación web gratuita para generar documentos legales de alta calidad. El generador de Términos y condiciones de PolicyMaker es una herramienta gratuita y fácil de usar para crear una excelente plantilla de Términos de servicio estándar para un sitio web, blog, tienda de comercio electrónico o aplicación.</p>
        <p>RECONOCE Y ACEPTA QUE LA COMPAÑÍA NO SERÁ RESPONSABLE NI RESPONSABLE, DIRECTA O INDIRECTAMENTE, DE CUALQUIER DAÑO O PÉRDIDA CAUSADA O QUE SE PRESUNTA CAUSADA POR O EN RELACIÓN CON EL USO O LA CONFIANZA EN CUALQUIER CONTENIDO, BIENES O SERVICIOS DISPONIBLES EN O A TRAVÉS DE CUALQUIER SITIO WEB O SERVICIOS DE TERCEROS.</p>
        <p>LE RECOMENDAMOS ENCARECIDAMENTE QUE LEA LOS TÉRMINOS DEL SERVICIO Y LAS POLÍTICAS DE PRIVACIDAD DE CUALQUIER SITIO WEB O SERVICIOS DE TERCEROS QUE VISITE.</p>
        <h4>19. Renuncia de garantía</h4>
        <p>ESTOS SERVICIOS SON PROPORCIONADOS POR LA EMPRESA "TAL CUAL" Y "SEGÚN DISPONIBILIDAD". LA COMPAÑÍA NO HACE REPRESENTACIONES NI GARANTÍAS DE NINGÚN TIPO, EXPRESAS O IMPLÍCITAS, EN CUANTO AL FUNCIONAMIENTO DE SUS SERVICIOS, O LA INFORMACIÓN, CONTENIDO O MATERIALES INCLUIDOS EN ELLOS. USTED ACEPTA EXPRESAMENTE QUE SU USO DE ESTOS SERVICIOS, SU CONTENIDO Y CUALQUIER SERVICIO O ARTÍCULO OBTENIDO DE NOSOTROS ES BAJO SU PROPIO RIESGO.</p>
        <p>NI LA ​​COMPAÑÍA NI LAS PERSONAS ASOCIADAS CON LA COMPAÑÍA OFRECEN NINGUNA GARANTÍA O REPRESENTACIÓN CON RESPECTO A LA INTEGRIDAD, SEGURIDAD, CONFIABILIDAD, CALIDAD, EXACTITUD O DISPONIBILIDAD DE LOS SERVICIOS. SIN LIMITAR LO ANTERIOR, NI LA ​​COMPAÑÍA NI NINGUNA PERSONA ASOCIADA CON LA COMPAÑÍA REPRESENTA O GARANTIZA QUE LOS SERVICIOS, SU CONTENIDO O CUALQUIER SERVICIO O ARTÍCULO OBTENIDO A TRAVÉS DE LOS SERVICIOS SERÁ EXACTO, CONFIABLE, LIBRE DE ERRORES O ININTERRUMPIDO, QUE LOS DEFECTOS SERÁN CORREGIDOS, QUE LOS SERVICIOS O EL SERVIDOR QUE LO PONE A DISPOSICIÓN ESTÁN LIBRES DE VIRUS U OTROS COMPONENTES DAÑINOS O QUE LOS SERVICIOS O CUALQUIER SERVICIO O ARTÍCULO OBTENIDO A TRAVÉS DE LOS SERVICIOS CUMPLIRÁN SUS NECESIDADES O EXPECTATIVAS.</p>
        <p>PRESENTE, LA COMPAÑÍA RENUNCIA A TODAS LAS GARANTÍAS DE CUALQUIER TIPO, YA SEA EXPLÍCITA O IMPLÍCITA, LEGAL O DE OTRO TIPO, INCLUIDAS, ENTRE OTRAS, CUALQUIER GARANTÍA DE COMERCIABILIDAD, NO INFRACCIÓN E IDONEIDAD PARA UN FIN DETERMINADO.</p>
        <p>LO ANTERIOR NO AFECTA NINGUNA GARANTÍA QUE NO PUEDE SER EXCLUIDA O LIMITADA BAJO LA LEY APLICABLE.</p>
        <h4>20. Limitación de responsabilidad</h4>
        <p>EXCEPTO POR LO PROHIBIDO POR LA LEY, USTED NOS EXONERARÁ A NOSOTROS Y A NUESTROS FUNCIONARIOS, DIRECTORES, EMPLEADOS Y AGENTES POR CUALQUIER DAÑO INDIRECTO, PUNITIVO, ESPECIAL, INCIDENTAL O CONSECUENTE, SIN EMBARGO QUE SURJA (INCLUYENDO HONORARIOS DE ABOGADOS Y TODOS LOS COSTOS RELACIONADOS Y GASTOS DE LITIGIO Y ARBITRAJE, O EN JUICIO O APELACIÓN, SI HAY, YA SE HAYA INSTITUIDO LITIGIO O ARBITRAJE O NO), YA SEA EN UNA ACCIÓN DE CONTRATO, NEGLIGENCIA U OTRA ACCIÓN Agraviosa, O QUE SURJA DE O EN CONEXIÓN CON ESTE ACUERDO, INCLUYENDO SIN LIMITACIÓN CUALQUIER RECLAMACIÓN POR LESIONES PERSONALES O DAÑOS A LA PROPIEDAD QUE SURJAN DE ESTE ACUERDO Y CUALQUIER VIOLACIÓN POR PARTE DE USTED DE CUALQUIER LEY, ESTATUTOS, REGLAS O REGLAMENTOS FEDERALES, ESTATALES O LOCALES, INCLUSO SI LA COMPAÑÍA HA SIDO PREVIAMENTE ADVERTIDA DE LA POSIBILIDAD DE TALES DAÑOS. SALVO LO PROHIBIDO POR LA LEY, SI EXISTE RESPONSABILIDAD POR PARTE DE LA COMPAÑÍA, ESTA SERÁ LIMITADA A LA CANTIDAD PAGADA POR LOS PRODUCTOS Y/O SERVICIOS, Y BAJO NINGUNA CIRCUNSTANCIA HABRÁ DAÑOS CONSECUENTES O PUNITIVOS. ALGUNOS ESTADOS NO PERMITEN LA EXCLUSIÓN O LIMITACIÓN DE DAÑOS PUNITIVOS, INCIDENTALES O CONSECUENTES, POR LO QUE LA LIMITACIÓN O EXCLUSIÓN ANTERIOR PUEDE NO SER APLICABLE A USTED.</p>
        <h4>21. Terminación</h4>
        <p>Podemos cancelar o suspender su cuenta y prohibir el acceso al Servicio de inmediato, sin previo aviso ni responsabilidad, a nuestro exclusivo criterio, por cualquier motivo y sin limitación, incluido, entre otros, el incumplimiento de los Términos.</p>
        <p>Si desea cancelar su cuenta, simplemente puede dejar de usar el Servicio.</p>
        <p>Todas las disposiciones de los Términos que, por su naturaleza, deberían sobrevivir a la rescisión sobrevivirán a la rescisión, incluidas, entre otras, las disposiciones de propiedad, las exenciones de garantía, la indemnización y las limitaciones de responsabilidad.</p>
        <h4>22. Ley aplicable</h4>
        <p>Estos Términos se regirán e interpretarán de acuerdo con las leyes de Zagreb, cuya ley aplicable se aplica al acuerdo sin tener en cuenta sus disposiciones sobre conflicto de leyes.</p>
        <p>El hecho de que no hagamos valer cualquier derecho o disposición de estos Términos no se considerará una renuncia a esos derechos. Si alguna disposición de estos Términos se considera inválida o inaplicable por un tribunal, las disposiciones restantes de estos Términos permanecerán en vigor. Estos Términos constituyen el acuerdo completo entre nosotros con respecto a nuestro Servicio y sustituyen y reemplazan cualquier acuerdo anterior que hayamos tenido entre nosotros con respecto al Servicio.</p>
        <h4>23. Cambios en el servicio</h4>
        <p>Nos reservamos el derecho de retirar o modificar nuestro Servicio, y cualquier servicio o material que proporcionemos a través del Servicio, a nuestro exclusivo criterio y sin previo aviso. No seremos responsables si, por algún motivo, la totalidad o parte del Servicio no está disponible en algún momento o durante algún período. De vez en cuando, podemos restringir el acceso a algunas partes del Servicio, o al Servicio completo, a los usuarios, incluidos los usuarios registrados.</p>
        <h4>24. Enmiendas a los Términos</h4>
        <p>Podemos modificar los Términos en cualquier momento publicando los términos modificados en este sitio. Es su responsabilidad revisar estos Términos periódicamente.</p>
        <p>Su uso continuado de la Plataforma luego de la publicación de los Términos revisados ​​significa que acepta y está de acuerdo con los cambios. Se espera que revise esta página con frecuencia para estar al tanto de cualquier cambio, ya que son vinculantes para usted.</p>
        <p>Al continuar accediendo o utilizando nuestro Servicio después de que las revisiones entren en vigencia, usted acepta estar sujeto a los términos revisados. Si no está de acuerdo con los nuevos términos, ya no está autorizado a utilizar el Servicio.</p>
        <h4>25. Renuncia y divisibilidad</h4>
        <p>Ninguna renuncia por parte de la Compañía a cualquier término o condición establecido en los Términos se considerará una renuncia adicional o continua de dicho término o condición o una renuncia a cualquier otro término o condición, y cualquier falla de la Compañía para hacer valer un derecho o disposición. bajo los Términos no constituirá una renuncia a tal derecho o disposición.</p>
        <p>Si un tribunal u otro tribunal de jurisdicción competente considera que alguna disposición de los Términos es inválida, ilegal o inaplicable por cualquier motivo, dicha disposición se eliminará o limitará en la medida mínima de manera que las disposiciones restantes de los Términos continúen. en pleno vigor y efecto.</p>
        <h4>26. Reconocimiento</h4>
        <p>AL UTILIZAR EL SERVICIO U OTROS SERVICIOS PROPORCIONADOS POR NOSOTROS, USTED RECONOCE QUE HA LEÍDO ESTOS TÉRMINOS DEL SERVICIO Y ACEPTA ESTAR OBLIGADO POR ELLOS.</p>
        <h4>27. Contáctenos</h4>
        <p>Envíe sus opiniones, comentarios y solicitudes de asistencia técnica por correo electrónico: iGamingPlatform@betting-support.com.</p>
    </div>
)